"""Constants for the learned segment-budget selector."""

LEARNED_SEGMENT_BUDGET_SCHEMA_VERSION = 2
LEARNED_SEGMENT_BUDGET_TRACE_SCHEMA_VERSION = 8
SEGMENT_ALLOCATION_WEIGHT_FLOOR = 0.50
GEOMETRY_TIE_BREAKER_WEIGHT = 0.12
SEGMENT_LENGTH_SUPPORT_ALLOCATION_WEIGHT = 0.12
SEGMENT_SCORE_POINT_BLEND_WEIGHT = 0.05
SEGMENT_TRANSFER_CALIBRATION_MODE_NONE = "none"
SEGMENT_TRANSFER_CALIBRATION_MODE_SCORE_ALLOCATION_ZBLEND = (
    "segment_score_allocation_weight_zblend"
)
SEGMENT_TRANSFER_CALIBRATION_MODE_CHOICES = (
    SEGMENT_TRANSFER_CALIBRATION_MODE_NONE,
    SEGMENT_TRANSFER_CALIBRATION_MODE_SCORE_ALLOCATION_ZBLEND,
)
