"""Fixtures for benchmark row field tests."""

from __future__ import annotations


def benchmark_row_run_json() -> dict[str, object]:
    return {
        "config": {
            "query": {
                "n_queries": 24,
                "target_coverage": 0.30,
                "max_queries": 512,
                "range_spatial_km": 2.2,
                "range_time_hours": 5.0,
                "range_train_workload_replicates": 3,
                "range_time_domain_mode": "anchor_day",
                "range_anchor_mode": "sparse",
                "range_train_anchor_modes": ["mixed_density", "sparse"],
                "range_train_footprints": ["1.1:2.5", "2.2:5.0"],
                "range_max_coverage_overshoot": 0.02,
            },
            "model": {
                "model_type": "range_aware",
                "historical_prior_k": 7,
                "historical_prior_mmsi_weight": 2.5,
                "historical_prior_source_aggregation": "mean",
                "mlqds_temporal_fraction": 0.25,
                "mlqds_diversity_bonus": 0.05,
                "mlqds_hybrid_mode": "swap",
                "mlqds_stratified_center_weight": 0.45,
                "mlqds_min_learned_swaps": 1,
                "mlqds_score_mode": "rank",
                "mlqds_score_temperature": 1.0,
                "mlqds_rank_confidence_weight": 0.15,
                "mlqds_range_geometry_blend": 0.25,
                "temporal_residual_label_mode": "temporal",
                "range_label_mode": "usefulness",
                "range_replicate_target_aggregation": "label_mean",
                "range_component_target_blend": 0.75,
                "range_temporal_target_blend": 0.15,
                "range_target_budget_weight_power": 0.50,
                "range_marginal_target_radius_scale": 0.65,
                "range_query_spine_fraction": 0.30,
                "range_query_spine_mass_mode": "query",
                "range_query_residual_multiplier": 1.25,
                "range_query_residual_mass_mode": "point",
                "range_set_utility_multiplier": 1.75,
                "range_set_utility_candidate_limit": 64,
                "range_set_utility_mass_mode": "query",
                "range_boundary_prior_weight": 0.0,
                "loss_objective": "budget_topk",
                "budget_loss_ratios": [0.01, 0.02, 0.05, 0.10],
                "budget_loss_temperature": 0.10,
                "temporal_distribution_loss_weight": 0.05,
                "checkpoint_full_score_every": 3,
                "checkpoint_candidate_pool_size": 2,
                "checkpoint_score_variant": "range_usefulness",
                "float32_matmul_precision": "high",
                "allow_tf32": True,
                "amp_mode": "bf16",
                "compression_ratio": 0.05,
            },
        },
        "oracle_diagnostic": {
            "kind": "additive_label_greedy",
            "exact_optimum": False,
        },
        "workload_blind_protocol": {
            "enabled": False,
            "primary_masks_frozen_before_eval_query_scoring": False,
            "audit_masks_frozen_before_eval_query_scoring": False,
            "eval_geometry_blend_allowed": True,
        },
        "final_claim_summary": {
            "primary_metric": "QueryLocalUtility",
            "status": "candidate_blocked_by_required_gates",
            "final_success_allowed": False,
            "blocking_gates": ["predictability_gate"],
        },
        "predictability_audit": {
            "gate_pass": False,
            "metrics": {
                "spearman": 0.12,
                "kendall_tau": 0.08,
                "lift_at_1_percent": 1.05,
                "lift_at_2_percent": 1.10,
                "lift_at_5_percent": 1.18,
                "pr_auc_lift_over_base_rate": 1.20,
            },
            "prior_predictive_alignment_gate": {
                "gate_pass": False,
                "failed_checks": ["query_hit_spearman_below_min"],
                "positive_spearman_head_count": 1,
            },
            "per_head_predictability": {
                "query_hit_probability": {
                    "spearman": 0.03,
                    "lift_at_5_percent": 1.04,
                    "pr_auc_lift_over_base_rate": 1.01,
                },
                "conditional_behavior_utility": {"spearman": -0.02, "lift_at_5_percent": 0.95},
                "replacement_representative_value": {"spearman": 0.08, "lift_at_5_percent": 1.06},
                "segment_budget_target": {"spearman": 0.01, "lift_at_5_percent": 1.02},
            },
            "prior_channel_predictability": {
                "query_mass_prior": {"spearman": 0.04},
                "combined_prior_score": {"lift_at_5_percent": 1.03},
            },
        },
        "workload_stability_gate": {
            "gate_pass": False,
            "failed_checks": ["train_r0:not_target_coverage_generation"],
            "train_workload_replicate_count": 1,
            "configured_target_coverage": 0.10,
        },
        "support_overlap_gate": {
            "gate_pass": True,
            "failed_checks": [],
            "eval_points_outside_train_prior_extent_fraction": 0.02,
            "sampled_prior_nonzero_fraction": 0.80,
            "primary_sampled_prior_nonzero_fraction": 0.60,
            "route_density_overlap": 0.70,
            "query_prior_support_overlap": 0.65,
            "train_eval_spatial_extent_intersection_fraction": 0.90,
        },
        "global_sanity_gate": {
            "gate_pass": True,
            "failed_checks": [],
            "endpoint_sanity": 1.0,
            "avg_sed_ratio_vs_uniform": 1.09,
            "avg_sed_ratio_vs_uniform_max": 1.50,
            "avg_length_preserved": 0.88,
        },
        "learning_causality_summary": {
            "learning_causality_ablation_status": "partial",
            "learning_causality_gate_pass": False,
            "learning_causality_failed_checks": ["shuffled_scores_should_lose"],
            "causality_ablation_missing": ["MLQDS_without_segment_budget_head"],
            "learned_controlled_retained_slot_fraction": 0.72,
            "planned_learned_controlled_retained_slot_fraction": 0.80,
            "actual_learned_controlled_retained_slot_fraction": 0.72,
            "trajectories_with_at_least_one_learned_decision": 5,
            "trajectories_with_zero_learned_decisions": 1,
            "segment_budget_entropy": 1.4,
            "segment_budget_entropy_normalized": 0.7,
            "selector_trace_retained_mask_matches_primary": True,
            "shuffled_score_ablation_delta": 0.04,
            "untrained_score_ablation_delta": 0.06,
            "shuffled_prior_field_ablation_delta": 0.05,
            "prior_field_only_score_ablation_delta": 0.02,
            "no_query_prior_field_ablation_delta": 0.03,
            "no_behavior_head_ablation_delta": 0.07,
            "no_segment_budget_head_ablation_delta": 0.08,
            "no_trajectory_fairness_preallocation_ablation_delta": 0.015,
            "no_geometry_tie_breaker_ablation_delta": -0.01,
            "no_segment_length_support_allocation_ablation_delta": 0.004,
            "causality_ablation_mask_diagnostics": {
                "MLQDS_shuffled_prior_fields": {
                    "retained_mask_jaccard": 0.82,
                    "retained_symmetric_difference_count": 12,
                },
                "MLQDS_without_query_prior_features": {
                    "retained_mask_jaccard": 0.74,
                    "retained_symmetric_difference_count": 18,
                },
                "MLQDS_without_behavior_utility_head": {
                    "retained_mask_jaccard": 0.97,
                    "retained_symmetric_difference_count": 2,
                },
                "MLQDS_without_segment_budget_head": {
                    "retained_mask_jaccard": 0.51,
                    "retained_symmetric_difference_count": 44,
                },
                "MLQDS_without_geometry_tie_breaker": {
                    "retained_mask_jaccard": 0.62,
                    "retained_symmetric_difference_count": 30,
                },
                "MLQDS_without_segment_length_support_allocation": {
                    "retained_mask_jaccard": 0.91,
                    "retained_symmetric_difference_count": 8,
                },
            },
            "learned_segment_selector_config": {
                "geometry_gain_weight": 0.12,
                "allocation_length_support_weight": 0.4,
                "allocation_weight_floor": 0.25,
                "segment_score_blend_weight": 0.05,
                "segment_transfer_calibration_mode": "segment_score_allocation_weight_zblend",
                "fairness_preallocation_enabled": True,
                "length_repair_fraction": 0.25,
                "length_repair_score_protection_fraction": 0.15,
                "length_support_blend_weight": 1.0,
            },
            "learning_causality_delta_gate": {
                "min_material_query_local_utility_delta": 0.005,
                "shuffled_score_delta_fraction_of_uniform_gap_min": 0.60,
                "mlqds_uniform_query_local_utility_gap": 0.05,
                "thresholds": {
                    "shuffled_scores_should_lose": 0.03,
                    "untrained_model_should_lose": 0.005,
                    "without_segment_budget_head_should_lose": 0.005,
                },
            },
            "segment_budget_head_ablation_mode": "neutral_constant_segment_scores",
            "prior_sample_gate_pass": False,
            "prior_sample_gate_failures": ["sampled_query_prior_features_all_zero"],
            "prior_sensitivity_diagnostics": {
                "shuffled_prior_fields": {
                    "sampled_prior_features": {
                        "sampled_inputs_changed": False,
                        "primary_nonzero_fraction": 0.0,
                        "ablation_nonzero_fraction": 0.01,
                        "mean_abs_feature_delta": 0.002,
                        "max_abs_feature_delta": 0.10,
                        "points_outside_prior_extent_fraction": 0.75,
                    },
                    "model_prior_features": {
                        "model_input_prior_features": {
                            "sampled_inputs_changed": True,
                            "mean_abs_feature_delta": 0.003,
                        },
                        "normalized_model_prior_features": {
                            "sampled_inputs_changed": True,
                            "mean_abs_feature_delta": 0.004,
                        },
                    },
                    "head_output": {
                        "head_logits_changed": True,
                        "mean_abs_head_logit_delta": 0.006,
                        "mean_abs_head_probability_delta": 0.0015,
                    },
                    "score_output": {
                        "mean_abs_score_delta": 0.012,
                        "max_abs_score_delta": 0.08,
                        "score_topk_jaccard_at_retained_count": 0.72,
                    },
                },
                "without_query_prior_features": {
                    "sampled_prior_features": {
                        "primary_nonzero_fraction": 0.0,
                        "mean_abs_feature_delta": 0.0,
                        "points_outside_prior_extent_fraction": 0.75,
                    },
                    "model_prior_features": {
                        "model_input_prior_features": {
                            "sampled_inputs_changed": False,
                            "mean_abs_feature_delta": 0.0,
                        },
                        "normalized_model_prior_features": {
                            "sampled_inputs_changed": False,
                            "mean_abs_feature_delta": 0.0,
                        },
                    },
                    "head_output": {
                        "head_logits_changed": False,
                        "mean_abs_head_logit_delta": 0.0,
                        "mean_abs_head_probability_delta": 0.0,
                    },
                    "score_output": {
                        "mean_abs_score_delta": 0.0,
                        "max_abs_score_delta": 0.0,
                        "score_topk_jaccard_at_retained_count": 1.0,
                    },
                },
            },
        },
        "query_generation_diagnostics": {
            "train": {
                "query_generation": {
                    "mode": "target_coverage",
                    "target_coverage": 0.20,
                    "final_coverage": 0.21,
                    "minimum_queries": 8,
                    "max_queries": 2048,
                    "final_query_count": 28,
                    "target_reached_query_count": 24,
                    "coverage_at_target_reached": 0.20,
                    "extra_queries_after_target_reached": 4,
                    "coverage_guard_enabled": True,
                    "max_allowed_coverage": 0.22,
                    "stop_reason": "target_coverage_reached",
                },
            },
            "eval": {
                "query_generation": {
                    "mode": "target_coverage",
                    "target_coverage": 0.20,
                    "final_coverage": 0.215,
                    "minimum_queries": 160,
                    "max_queries": 2048,
                    "final_query_count": 160,
                    "target_reached_query_count": 31,
                    "coverage_at_target_reached": 0.201,
                    "extra_queries_after_target_reached": 129,
                    "coverage_guard_enabled": True,
                    "max_allowed_coverage": 0.22,
                    "stop_reason": "target_coverage_reached",
                },
            },
            "selection": {
                "query_generation": {
                    "mode": "target_coverage",
                    "target_coverage": 0.20,
                    "final_coverage": 0.205,
                    "minimum_queries": 8,
                    "max_queries": 2048,
                    "final_query_count": 21,
                    "target_reached_query_count": 21,
                    "coverage_at_target_reached": 0.205,
                    "extra_queries_after_target_reached": 0,
                    "coverage_guard_enabled": True,
                    "max_allowed_coverage": 0.22,
                    "stop_reason": "target_coverage_reached",
                },
            },
        },
        "teacher_distillation": {
            "enabled": True,
            "mode": "retained_frequency",
            "teacher_model_type": "range_aware",
            "replicate_count": 4,
            "positive_label_count": 120,
            "positive_label_fraction": 0.25,
            "positive_label_mass": 16.0,
        },
        "workload_distribution_comparison": {
            "workload_signature_gate": {
                "all_available": True,
                "all_pass": False,
                "pairs": {
                    "train": {
                        "metrics": {
                            "anchor_family_l1_distance": 0.16,
                            "footprint_family_l1_distance": 0.05,
                            "point_hit_distribution_ks": 0.22,
                            "ship_hit_distribution_ks": 0.10,
                            "point_hit_fraction_distribution_ks": 0.12,
                            "ship_hit_fraction_distribution_ks": 0.08,
                            "query_count_delta": 8,
                            "query_count_relative_delta": 0.125,
                            "train_total_points": 1000,
                            "eval_total_points": 500,
                            "train_total_trajectories": 20,
                            "eval_total_trajectories": 10,
                            "point_hit_distribution_used_quantile_proxy": False,
                            "ship_hit_distribution_used_quantile_proxy": False,
                        }
                    }
                },
            },
            "summaries": {
                "train": {
                    "range_query_count": 28,
                    "coverage_fraction": 0.21,
                    "near_duplicate_query_rate": 0.10,
                    "point_hit_count_p50": 30.0,
                    "trajectory_hit_count_p50": 2.0,
                    "oracle_gap_over_best_baseline": 0.20,
                    "best_baseline": "uniform",
                },
                "eval": {
                    "range_query_count": 160,
                    "coverage_fraction": 0.215,
                    "empty_query_rate": 0.02,
                    "too_broad_query_rate": 0.03,
                    "near_duplicate_query_rate": 0.40,
                    "point_hit_count_p50": 24.0,
                    "trajectory_hit_count_p50": 3.0,
                    "oracle_gap_over_best_baseline": 0.25,
                    "best_baseline": "DouglasPeucker",
                },
                "selection": {
                    "range_query_count": 21,
                    "coverage_fraction": 0.205,
                    "near_duplicate_query_rate": 0.05,
                    "point_hit_count_p50": 18.0,
                    "trajectory_hit_count_p50": 2.0,
                    "oracle_gap_over_best_baseline": 0.22,
                    "best_baseline": "uniform",
                },
            },
        },
        "workload_diagnostics": {
            "train": {
                "range_signal": {
                    "labels": {
                        "positive_label_mass": 12.5,
                        "component_label_mass_basis": "pre_clamp_component_contributions",
                        "component_positive_label_mass_fraction": {
                            "range_point_f1": 0.22,
                            "range_ship_f1": 0.13,
                            "range_ship_coverage": 0.12,
                            "range_entry_exit_f1": 0.09,
                            "range_crossing_f1": 0.04,
                            "range_temporal_coverage": 0.11,
                            "range_gap_coverage": 0.10,
                            "range_turn_coverage": 0.08,
                            "range_shape_score": 0.11,
                        },
                    }
                }
            }
        },
        "training_target_diagnostics": {
            "positive_label_mass": 11.0,
            "historical_prior_source_count": 4,
            "historical_prior_stored_support_count": 1234,
            "budget_rows": [
                {
                    "total_budget_ratio": 0.01,
                    "effective_fill_budget_ratio": 0.008,
                    "temporal_base_label_mass_fraction": 0.20,
                    "residual_label_mass_fraction": 0.80,
                    "residual_positive_label_fraction": 0.10,
                },
                {
                    "total_budget_ratio": 0.05,
                    "effective_fill_budget_ratio": 0.041,
                    "temporal_base_label_mass_fraction": 0.35,
                    "residual_label_mass_fraction": 0.65,
                    "residual_positive_label_fraction": 0.20,
                },
            ],
        },
        "training_fit_diagnostics": {
            "score_target_kendall_tau": 0.31,
            "matched_mlqds_target_recall": 0.74,
            "matched_uniform_target_recall": 0.62,
            "matched_mlqds_vs_uniform_target_recall": 0.12,
            "low_budget_mean_mlqds_vs_uniform_target_recall": -0.04,
        },
        "range_training_target_transform": {
            "mode": "local_swap_utility_frequency",
            "positive_label_count": 17,
            "positive_label_fraction": 0.25,
            "positive_label_mass": 3.5,
            "local_swap_utility_scored_candidate_count": 40,
            "local_swap_utility_positive_gain_candidate_count": 11,
            "local_swap_utility_selected_count": 7,
            "local_swap_utility_selected_gain_mass": 1.25,
            "local_swap_utility_source_positive_mass": 3.5,
            "local_swap_gain_cost_scored_candidate_count": 44,
            "local_swap_gain_cost_positive_net_gain_count": 12,
            "local_swap_gain_cost_selected_count": 8,
            "local_swap_gain_cost_selected_candidate_value_mass": 1.50,
            "local_swap_gain_cost_selected_removal_cost_mass": 0.40,
            "local_swap_gain_cost_source_positive_mass": 3.75,
        },
        "matched": {
            "MLQDS": {
                "aggregate_f1": 0.40,
                "query_point_recall": 0.31,
                "range_point_f1": 0.40,
                "range_usefulness_score": 0.42,
                "query_local_utility_score": 0.46,
                "range_ship_f1": 0.60,
                "range_ship_coverage": 0.64,
                "range_entry_exit_f1": 0.25,
                "range_crossing_f1": 0.48,
                "range_temporal_coverage": 0.58,
                "range_gap_coverage": 0.31,
                "range_gap_time_coverage": 0.41,
                "range_gap_distance_coverage": 0.36,
                "range_gap_min_coverage": 0.36,
                "range_turn_coverage": 0.52,
                "range_shape_score": 0.44,
                "range_usefulness_schema_version": 7,
                "range_usefulness_gap_time_score": 0.429,
                "range_usefulness_gap_distance_score": 0.4245,
                "range_usefulness_gap_min_score": 0.4245,
                "range_usefulness_gap_ablation_version": 1,
                "geometric_distortion": {
                    "avg_sed_km": 0.60,
                    "max_sed_km": 4.0,
                    "avg_ped_km": 0.20,
                    "max_ped_km": 2.0,
                    "removed_points": 90,
                },
                "avg_length_preserved": 0.88,
                "latency_ms": 8.0,
            },
            "uniform": {
                "aggregate_f1": 0.35,
                "query_point_recall": 0.26,
                "range_point_f1": 0.35,
                "range_usefulness_score": 0.37,
                "query_local_utility_score": 0.39,
                "range_ship_f1": 0.50,
                "range_ship_coverage": 0.60,
                "range_entry_exit_f1": 0.30,
                "range_crossing_f1": 0.47,
                "range_temporal_coverage": 0.62,
                "range_gap_coverage": 0.40,
                "range_gap_time_coverage": 0.50,
                "range_gap_distance_coverage": 0.48,
                "range_gap_min_coverage": 0.48,
                "range_turn_coverage": 0.51,
                "range_shape_score": 0.50,
                "range_usefulness_gap_time_score": 0.379,
                "range_usefulness_gap_distance_score": 0.3772,
                "range_usefulness_gap_min_score": 0.3772,
                "geometric_distortion": {
                    "avg_sed_km": 0.55,
                    "max_sed_km": 3.5,
                    "avg_ped_km": 0.18,
                    "max_ped_km": 1.7,
                    "removed_points": 90,
                },
                "avg_length_preserved": 0.91,
                "latency_ms": 2.0,
            },
            "DouglasPeucker": {
                "aggregate_f1": 0.36,
                "query_point_recall": 0.29,
                "range_point_f1": 0.36,
                "range_usefulness_score": 0.39,
                "query_local_utility_score": 0.41,
                "range_ship_f1": 0.48,
                "range_ship_coverage": 0.55,
                "range_entry_exit_f1": 0.28,
                "range_crossing_f1": 0.42,
                "range_temporal_coverage": 0.51,
                "range_gap_coverage": 0.22,
                "range_gap_time_coverage": 0.30,
                "range_gap_distance_coverage": 0.26,
                "range_gap_min_coverage": 0.26,
                "range_turn_coverage": 0.49,
                "range_shape_score": 0.35,
                "range_usefulness_gap_time_score": 0.3972,
                "range_usefulness_gap_distance_score": 0.3936,
                "range_usefulness_gap_min_score": 0.3936,
                "geometric_distortion": {
                    "avg_sed_km": 0.45,
                    "max_sed_km": 3.0,
                    "avg_ped_km": 0.15,
                    "max_ped_km": 1.2,
                    "removed_points": 90,
                },
                "avg_length_preserved": 0.93,
                "latency_ms": 3.0,
            },
        },
        "range_compression_audit": {
            "0.0100": {
                "MLQDS": {
                    "range_usefulness_score": 0.10,
                    "query_local_utility_score": 0.11,
                    "range_usefulness_gap_time_score": 0.11,
                },
                "uniform": {
                    "range_usefulness_score": 0.12,
                    "query_local_utility_score": 0.13,
                    "range_usefulness_gap_time_score": 0.10,
                },
                "DouglasPeucker": {
                    "range_usefulness_score": 0.09,
                    "query_local_utility_score": 0.10,
                },
                "TemporalRandomFill": {"range_usefulness_score": 0.11},
            },
            "0.0500": {
                "MLQDS": {
                    "range_usefulness_score": 0.42,
                    "query_local_utility_score": 0.46,
                    "range_usefulness_gap_time_score": 0.43,
                },
                "uniform": {
                    "range_usefulness_score": 0.37,
                    "query_local_utility_score": 0.39,
                    "range_usefulness_gap_time_score": 0.38,
                },
                "DouglasPeucker": {
                    "range_usefulness_score": 0.39,
                    "query_local_utility_score": 0.41,
                },
                "TemporalRandomFill": {"range_usefulness_score": 0.41},
            },
            "0.1000": {
                "MLQDS": {"range_usefulness_score": 0.50, "query_local_utility_score": 0.52},
                "uniform": {"range_usefulness_score": 0.48, "query_local_utility_score": 0.49},
                "DouglasPeucker": {
                    "range_usefulness_score": 0.47,
                    "query_local_utility_score": 0.48,
                },
                "TemporalRandomFill": {"range_usefulness_score": 0.52},
            },
        },
        "learned_fill_diagnostics": {
            "TemporalRandomFill": {
                "range_point_f1": 0.38,
                "range_usefulness_score": 0.41,
            },
            "TemporalOracleFill": {
                "range_point_f1": 0.55,
                "range_usefulness_score": 0.70,
            },
        },
        "best_epoch": 2,
        "best_selection_score": 0.42,
        "training_history": [
            {
                "epoch": 0.0,
                "loss": 1.0,
                "pred_std": 0.0,
                "kendall_tau_t0": 0.1,
                "collapse_warning": 1.0,
                "epoch_forward_seconds": 0.2,
                "epoch_loss_seconds": 0.4,
                "epoch_backward_seconds": 0.3,
                "epoch_diagnostic_seconds": 0.1,
                "epoch_validation_score_seconds": 0.0,
            },
            {
                "epoch": 1.0,
                "loss": 0.8,
                "pred_std": 0.2,
                "kendall_tau_t0": 0.2,
                "epoch_forward_seconds": 0.4,
                "epoch_loss_seconds": 0.6,
                "epoch_backward_seconds": 0.5,
                "epoch_diagnostic_seconds": 0.3,
                "epoch_validation_score_seconds": 0.7,
            },
        ],
        "torch_runtime": {
            "float32_matmul_precision": "high",
            "tf32_matmul_allowed": True,
            "tf32_cudnn_allowed": True,
            "amp": {"enabled": True, "dtype": "bfloat16"},
        },
    }
